### ISSUE TITLE
CelebA-HQ 256 Dataset

### ISSUE THREAD

**Issue by leoliu37** [NVlabs/NVAE#13]
Thanks for the interesting work.

I want to reproduce the NVAE model in CelebAHQ 256 dataset. Could you provide the main NVAE training scripts with detailed parameters in the Celeba-HQ dataset? 

Thanks for your help.

**Comment by arash-vahdat** [comment]
We just updated the README with the training commands for all the datasets, in addition to the pre-trained checkpoints.

**Comment by leoliu37** [comment]
> We just updated the README with the training commands for all the datasets, in addition to the pre-trained checkpoints.

Thanks for your help.
