### ISSUE TITLE
num_latent_scales on ImageNet 32x32 dataset

### ISSUE THREAD

**Issue by liuyuyuil** [NVlabs/NVAE#20]
Thanks for sharing your code. I have found that the hyper-parameter 'num_latent_scales' on ImageNet 32x32 and CIFAR-10 has been set to be 1, which is quite smaller than that of 5 on FFHQ and CelebA HQ dataset. What will happen if we set this number as 5 on ImageNet 32x32 dataset ? Thanks~

**Comment by arash-vahdat** [comment]
The number of latent scales represents the number of latent scales in the latent space. For CIFAR-10, we have only one scale at 16x16 dimensions. We didn't see improvements in terms of log-likelihood for using multi-scale latent space.
