### ISSUE TITLE
FID score?

### ISSUE THREAD

**Issue by Tsingularity** [NVlabs/NVAE#23]
Hi thanks for the great work!

I am just wondering do you have plans for releasing the FID scores on varying datasets for NVAE?

Thanks!

**Comment by arash-vahdat** [comment]
Hi 

We did report FID scores for some of the NVAE models in the follow-up works. Please check these two papers:
- https://arxiv.org/abs/2010.00654
- https://arxiv.org/abs/2010.02917

Thanks!
