### ISSUE TITLE
Can you provide pretrained models?

### ISSUE THREAD

**Issue by kopepod** [NVlabs/NVAE#34]
Hi, I have no that powerful resources to train the models (2GPUs), could you provide pretrained models for evaluations purposes regarding the latent space? Thanks.

**Comment by arash-vahdat** [comment]
We have released checkpoints on the MNIST, CIFAR-10, CelebA 64, CelebA HQ 256, and FFHQ datasets. Check [here](https://github.com/NVlabs/NVAE#post-training-sampling-evaluation-and-checkpoints) on the readme.
